version: '3.8'

services:
    redis:
        image: redis
        ports:
            - 6379:6379
    sys_backend:
        build: .
        ports:
            - 8089:8089
        depends_on:
            - redis
        network_mode: "host"
