version: '3.12'

services:
    redis:
        image: redis
        ports:
            - 6380:6379
    sys_backend:
        build: .
        ports:
            - 8089:8089
        depends_on:
            - redis