# ============================================
#                                           
#   Project Name :  be_sistem_pakar               
#   -------------------------------------   
#   Create by    : hexa at 13/05/24       
#   Copyright © 2024 Delameta Bilano     
#                                           
# ============================================
import io
import os

from fastapi import APIRouter
from starlette.responses import Response, StreamingResponse

assets = APIRouter(tags=['Assets Router'], prefix='/assets')
@assets.get(
    "",

    # Set what the media type will be in the autogenerated OpenAPI specification.
    # fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response
    responses = {
        200: {
            "content": {"image/png": {}}
        }
    },

    # Prevent FastAPI from adding "application/json" as an additional
    # response media type in the autogenerated OpenAPI specification.
    # https://github.com/tiangolo/fastapi/issues/3258

)
def get_image(images):

    try:
        image_bytes = open(os.path.join("uploads",images), "rb").read()
    except FileNotFoundError:
        image_bytes = open(os.path.join("uploads",'img.png'), "rb").read()

        # return Response(status_code=404)
    image_stream = io.BytesIO(image_bytes)
    return StreamingResponse(content=image_stream, media_type="image/png")